### ISSUE TITLE
Stuck with Storeman 0.1.8 on SFOS 3.2.1?

### ISSUE THREAD

**Issue by Olf0** [mentaljam/harbour-storeman#132]
Intro: 
Because SFOS 3.3.0 exposes some significant issues (e.g., SD-card inaccessible for Android apps), my "productive phone" (an Xperia X) is still on SFOS 3.2.1 (and it looks like I will have to avoid SFOS 3.4.0 for "productive" use, too).
On this phone no update of Storeman was offered (in Storeman) beyond v0.1.8, which is O.K., as I assumed the newer versions of Storeman to have new or updated dependencies or being compiled with a newer SDK for SFOS >= 3.3.0.

Question: 
Now your new changelog entry confuses me.
```
2020-02-04 • 0.2.2-1

    Fix duplicate results in search list
    Update translations
    Provide separate builds for SFOS <=3.3 and >=3.4
```
Does "Provide separate builds for SFOS <=3.3 and >=3.4" mean I should be able to update to *harbour-storeman-0.2.2-1~sfos3.3.armv7hl* on SFOS 3.2.1?
Or should this changelog entry rather read "Provide separate builds for SFOS =3.3 and >=3.4" (i.e., with the "<" deleted)?

P.S.: The date also looks wrong, I suppose it should be "2020-10-04" (instead of "2020-02-04").

**Comment by mentaljam** [comment]
The sfos3.3 branch is built with 3.3.0.14 target. It's RPM depends on OS version [<=3.3](https://github.com/mentaljam/harbour-storeman/blob/79068c2ee18fc3fb9b8bc7947db265e901009298/rpm/harbour-storeman.spec#L10). I can create a new branch for your version of SFOS if you cannot upgrade Storeman to any version after 0.1.8.

**Comment by mentaljam** [comment]
> P.S.: The date also looks wrong, I suppose it should be "2020-10-04" (instead of "2020-02-04").

Fixed, thank you :)

**Comment by Olf0** [comment]
... or simply delete the "<" in the changelog entry (plus correcting the date) here at Github and at Openrepos.
Either way is fine for me.
I would suggest to pick the easier one. ;-)

**Comment by Olf0** [comment]
> The sfos3.3 branch is built with 3.3.0.14 target. It's RPM depends on OS version [<=3.3](https://github.com/mentaljam/harbour-storeman/blob/79068c2ee18fc3fb9b8bc7947db265e901009298/rpm/harbour-storeman.spec#L10). I can create a new branch for your version of SFOS if you cannot upgrade Storeman to any version after 0.1.8.

Now tested manually with `pkcon update`:
- `pkcon update storeman` fails with an unmet dependency to `libstdc++.so.6(CXXABI_1.3.9)`, due to trying to install `harbour-storeman-0.2.2-1` (which is the version for SFOS >= 3.4.0).
- `pkcon update "harbour-storeman-0.2.2-1~sfos3.3"`, `pkcon update "harbour-storeman-0.2.2-1~sfos3_.3"`, `pkcon update "harbour-storeman-0.2.2-1~sfos3_"`, and `pkcon update "harbour-storeman-0.2.2-1~sfos3"` all fail with "package not found".

Maybe I am just too dumb to tell `pkcon`, which version it should update to.

**Comment by Olf0** [comment]
So I downloaded *harbour-storeman-0.2.2-1~sfos3_.3.armv7hl.rpm* from Openrepos and tried to install it per `pkcon install-local harbour-storeman-0.2.2-1~sfos3_.3.armv7hl.rpm`.
It also still fails with 
```

```

**Comment by Olf0** [comment]
Look as if loosely related to https://github.com/mentaljam/harbour-storeman/issues/108#issuecomment-684969668
From there I can tell, that a dependency to `libstdc++.so.6(CXXABI_1.3)` can be fulfilled (but not to `libstdc++.so.6(CXXABI_1.3.9)`).

**Comment by mentaljam** [comment]
Storeman should be built with the appropriate SDK target. Unfortunately current branch of Storeman cannot be compiled with 3.2 as I switched to C++17 which is not available on 3.2. I will create a separate branch for 3.2 and revert some changes in code to compile it with an old compiler.

**Comment by mentaljam** [comment]
Could you please check this version?
[harbour-storeman-0.2.2-1~sfos3.2.armv7hl.rpm.zip](https://github.com/mentaljam/harbour-storeman/files/5332117/harbour-storeman-0.2.2-1.sfos3.2.armv7hl.rpm.zip)

**Comment by Olf0** [comment]
Thank you!
It installs fine and also installs the Salfish-Secrets and a couple of other new RPMs as dependencies (as expected).
Just did a quick test: Everything seems to be working perfectly, except for the order of the top window entries (while "My repository" is new, the order of all entries was reset; so I reordererd them, again).

**Comment by Olf0** [comment]
> Storeman should be built with the appropriate SDK target. Unfortunately current branch of Storeman cannot be compiled with 3.2 as I switched to C++17 which is not available on 3.2. I will create a separate branch for 3.2 **and revert some changes in code to compile it with an old compiler**.

Are you sure, that this maintenance burden is worth it?
Apparently using C++17 features in Storeman's code is helpful for you, so either you split the code-base in two diverging branches (pre-3.3 and 3.3+; sounds as you are about to do that, which results in maintaining two branches) or you eliminate the use of C++17 features (so a single branch covers pre- and post-SFOS3.3), which you started to use for a reason.

While I appreciate the vast infrastructure updates in SFOS 3.2.x, 3.3 and 3.4 (GCC, tools, UNIX utilities, AlienDalvik8 etc.), their big code churn introduced a large number of new bugs (as usual).
IMO it is Jolla's responsibility to take care about quality assurance, but they regard all private SFOS users as beta-testers, only their institutional users (basically they only have one) are regarded as customers (BTW, that was explicitly stated so by James Noori @TJC and @IRC).  Hence no real QA by Jolla for us, only "smoke tests".  Still, I would be on the recent SFOS release, if it would be working for me (rsp. the feature set of SFOS I use).

**Comment by mentaljam** [comment]
For now it doesn't look too hard: 8401e84. Most errors were fixed by enabling C++14. If maintenance of SFOS 3.2 become too heavy for me I'll try to search some help or just abandon it ¯\_(ツ)_/¯.

**Comment by Olf0** [comment]
That's fine for me.

My point simply is: I appreciate your work a lot, so I rather would like to see your efforts being primarily aimed at enhancements than legacy compatibility.

**Comment by Olf0** [comment]
> For now it doesn't look too hard: [8401e84](https://github.com/mentaljam/harbour-storeman/commit/8401e846869bd67fe041cc402c541c14c7e80538).

Oh, that is really not much.
Others (e.g., rinigus' PureMaps) were quickly using a lot of C++17 features, hence I assumed more of these being used since Storeman 0.1.8, too.

**Comment by TJC** [comment]
hey folks, you tagged me into this conversation, but I'm mostly just confused, so am gonna drop out now. Cheers

**Comment by Olf0** [comment]
> hey folks, you tagged me into this conversation, ...

Sorry, my bad.
I meant "(at)Together.Jolla.com" and wrote "\@TJC", thereby addressing you.

**Comment by Olf0** [comment]
@mentaljam, I did the same (multiple release branches resulting in multiple, OS version dependent release versions) with [crypto-sdcard](https://github.com/Olf0/crypto-sdcard) and encountered strange issues with the release versions' order (by lexicographic sorting) and necessary dependency counterparts (seemingly similar to the ones [reported](https://github.com/mentaljam/harbour-storeman/issues/132#issuecomment-703691488) and [resolved](https://github.com/mentaljam/harbour-storeman/issues/132#issuecomment-704094744) here) after uploading them to he same RPM repository.
After some research and testing I finally (hope to have) resolved these issuey, summarising my observations and conclusions in this ad hoc documentation "[Release version format, RPM dependencies and Git workflow](https://github.com/Olf0/crypto-sdcard/blob/master/RPM-dependencies_Git-workflow.md)".  HTH.
